# Site settings
title: Denny's Blog
header-img: img/home-bg.jpg
email: dennyac@gmail.com
description: "Denny's Blog!"
baseurl: ""
url: "http://dennyac.com"
twitter_username: d3nnyac
github_username:  dennyac
facebook_username:  dennyac

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
