# Site settings
title: Denny's Blog
header-img: img/home-bg.jpg
email: dennyac@gmail.com
description: "Tech Blog"
baseurl: ""
url: "http://dennyac.com"
twitter_username: d3nnyac
github_username:  dennyac
facebook_username:  dennyac
youtube_url: "https://www.youtube.com/channel/UCyFOdJqkeHe8xhiSjTdmh3g"
stackoverflow_url: "http://stackoverflow.com/users/2072191/denny-abraham-cheriyan"
linkedin_url: "https://www.linkedin.com/in/dennyac"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#For sitemap generation	
gems:
  - jekyll-sitemap
